FROM openjdk:8u212-jdk-stretch

ENV YCSB_DIR /app/ycsb
ENV OUTPUT_FILE_NAME out
ENV PREFIX prefix
ENV MEASUREMENT_RESULTS_DIR /ycsb

RUN apt-get update && apt-get install -y \
  git \
  maven \
  build-essential

COPY . $YCSB_DIR

ADD ./entrypoint_parse.sh /

WORKDIR /app

RUN git clone https://github.com/vishnubob/wait-for-it.git

RUN mkdir ${MEASUREMENT_RESULTS_DIR}

VOLUME ${MEASUREMENT_RESULTS_DIR}

ENTRYPOINT ["/entrypoint_parse.sh"]